### PR TITLE
Add <supports_no_game> tag

### PR DESCRIPTION
**Pull request by eibma**
Core is not chosen as possible candidate if this flag is not set

### CODE REVIEW

**Comment by notspiff** [comment]
this seems wrong. afaik this flag is for standalone games.@garbear ?

**Comment by notspiff** [comment]
i should read the diff before commenting. thanks.

**Comment by eibma** [comment]
But setting it to false should state the fact that a rom is needed afaik. Check GameClient.cpp line 217. This is returning false for this core.

**Comment by notspiff** [comment]
only on mobile here and while i remember. could you send a pull to garbear/xbmc initializing the var in InitializeProperties() so this doesnt burn us again please?

**Pull request merged**
